//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conkurs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user17_PetrovEntities : DbContext
    {
        public static user17_PetrovEntities _context;
        public user17_PetrovEntities()
            : base("name=user17_PetrovEntities")
        {
        }
        public static user17_PetrovEntities GetContext()
        {
            if(_context == null)
            {
                _context= new user17_PetrovEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Active> Active { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Jury> Jury { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Meropr> Meropr { get; set; }
        public virtual DbSet<Moderator> Moderator { get; set; }
        public virtual DbSet<Napr> Napr { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
